WS_INTEGRATION/mdapi_output_dir/objects/Division__c.object
<CustomObject>
    <description>Flat table that is manually maintained by the admin. This table handles the list of Campus, School, Unit, Department, and Cost Center</description>
    <label>Division</label>
    <nameField>
        <displayFormat>Div-{0}</displayFormat>
        <label>Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

WS_INTEGRATION/DX Sandbox/src/classes/Division.cls
public class Division {
    
    public void nameDivision(Division__c[] newDivision){
        string newName;  
        
        for(Division__c div : newDivision) {
            //Sometimes cost centers are null, so set those as just the department
            if(String.isBlank(div.Cost_Center__c)){
                newName = div.Department__c;
            } else {
                newName = div.Cost_Center__c;
            }
            
            div.Name = newName;
        }        
    }    
}