WS_INTEGRATION/mdapi_output_dir/objects/Division2Contact__c.object
<CustomObject>
    <description>Junction object for Division and Contact. NOT Master-Detail</description>
    <label>Division2Contact</label>
    <nameField>
        <label>Division2Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Division2Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Division2Contacts</relationshipLabel>
        <relationshipName>Divisions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Division</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Division__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Defaulted to only include active Divisions. This filter can be removed.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Division2Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

WS_INTEGRATION/mdapi_output_dir/objects/Division__c.object
<CustomObject>
    <description>Flat table that is manually maintained by the admin. This table handles the list of Campus, School, Unit, Department, and Cost Center</description>
    <label>Division</label>
    <nameField>
        <displayFormat>Div-{0}</displayFormat>
        <label>Division Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/mdapi_output_dir/objects/Invention_Junction__c.object
<CustomObject>
    <description>Connects Inventions to Accounts, Contacts, and Divisions</description>
    <label>Invention Junction</label>
    <nameField>
        <label>Invention Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Inventions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Division</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

WS_INTEGRATION/mdapi_output_dir/classes/inventionContactController.cls
public class inventionContactController {
    @AuraEnabled
    public static List<RelatedObject> getRelDivisions(String givenId){
        System.debug('getRelDivisions method starting...');
        System.debug('The givenID is: ' + givenId);
        
        //List to hold the final values
        List<RelatedObject> pickListValuesList = new List<RelatedObject>();
        
        //Make sure there is an id for contact
        if(String.isblank(givenID)){
            String.valueof(Database.query('SELECT Contact__c FROM Division2Contact__c LIMIT 1'));}
        //givenID = '0031D000001tqHyQAI';
        
        
        //List to hold the junction object results
        List<Division2Contact__c> relJunctionObjects = [SELECT Division__c,Division__r.Name FROM Division2Contact__c WHERE Contact__c = :givenId];
            //new Set<id>();
            //Database.query('SELECT Division__c FROM Division2Contact__c WHERE Contact__c = ' + givenId);
        System.debug('relJunctionObjects List contains: ' + relJunctionObjects);
        
        //Add the results into the String list
        for(Division2Contact__c s: relJunctionObjects) {
            pickListValuesList.add(new RelatedObject(s.Division__c,s.Division__r.Name));            
        } 
        
        //for(Integer i=0; i<relJunctionObjects.size(); i++) {
        //    pickListValuesList.add(StringValueof(new Division2Contact__c(relJunctionObjects.Division__c[i],Division__r.Name[i])));
        
        system.debug('pickListValuesList = ' + pickListValuesList);
        return pickListValuesList;
    }
}