WS_INTEGRATION/mdapi_output_dir/objects/Invention__c.object
<CustomObject>
    <description>Publicly disclosed inventions from KU</description>
    <label>Invention</label>
    <nameField>
        <label>Invention Track Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/DX Sandbox/src/objects/Invention__c.object
    <fields>
        <fullName>Invention_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invention Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions (Invention Contact)</relationshipLabel>
        <relationshipName>Inventions</relationshipName>
        <type>Lookup</type>
    </fields>

WS_INTEGRATION/mdapi_output_dir/objects/Invention_Contact__c.object
<CustomObject>
    <description>Connects Inventions to Contacts</description>
    <label>Invention Contact</label>
    <nameField>
        <label>Invention Researcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Invention__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Invention</label>
        <referenceTo>Invention__c</referenceTo>
        <relationshipLabel>Researchers</relationshipLabel>
        <relationshipName>Invention_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Researcher__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Researcher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Invention_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

WS_INTEGRATION/force-app/main/default/classes/InventionContact.cls
public class InventionContact {
    public void newInvContName(Invention_Contact__c[] newInvCont){
        string newName;
        string contactName;
        string inventionTrackCode;
        Set<id> contSearch = new Set<id>();
        Map<Id,String> nameMap = new Map<Id,String>();
        
        //Information about the related Invention
        Set<id> invSearch = new Set<id>();
        
        for(Invention_Contact__c z : newInvCont){
            invSearch.add(z.Invention__c);
            contSearch.add(z.Researcher__c);
        }
        
        List<Invention__c> invList = [SELECT name FROM Invention__c WHERE id IN :invSearch ];
        
        for(Invention__c inv:invList){
            nameMap.put(inv.Id,inv.Name);
        }
        
        List<Contact> contList = [SELECT LastName FROM Contact WHERE id IN :contSearch ];
        
        for(Contact con:contList){
            nameMap.put(con.Id,con.LastName);
        }

        //List of records to update
        List<Invention_Contact__c> updateList = new List<Invention_Contact__c>();
        
        //Update the name for each record
        for(Invention_Contact__c a : newInvCont){
            newName = nameMap.get(a.Invention__c) + '-' + nameMap.get(a.Researcher__c);
            a.Name = newName;
        }
        
    }
}