WS_INTEGRATION/mdapi_output_dir/objects/Invention__c.object
<CustomObject>
    <description>Publicly disclosed inventions from KU</description>
    <label>Invention</label>
    <nameField>
        <label>Invention Track Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Campus__c</fullName>
        <description>Defines the Letter on the end of the Track Code</description>
        <label>Campus</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Campus</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Anticipated</fullName>
        <active>true</active>
        <description>This invention has not been disclosed formally to KU.</description>
        <label>Anticipated</label>
    </recordTypes>
</CustomObject>

WS_INTEGRATION/force-app/main/default/globalValueSets/Campus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kansas City Medical Center</fullName>
    </customValue>
    <customValue>
        <fullName>Lawrence</fullName>
    </customValue>
    <customValue>
        <fullName>Wichita</fullName>
    </customValue>
    <description>List of all the different campuses in KU</description>
    <masterLabel>Campus</masterLabel>
</GlobalValueSet>

WS_INTEGRATION/mdapi_output_dir/classes/inventionAura.cls
public class inventionAura {
//Pull the record type picklist values-----------------------------------------------------------------------------------------------
    @AuraEnabled    
    public static List<String> getCampusValues(){
        System.debug('getCampusValues() Running...');
        List<String> campusValue = new List<String>();
        
        Schema.DescribeFieldResult fieldResult = Invention__c.Campus__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for(Schema.PicklistEntry f: ple){
            campusValue.add(f.getLabel());
        }
        
        return campusValue;
    }
    
    //Get Record Type ID ------------------------------------------
    @AuraEnabled
    public static String getRecordTypeId() {
        System.debug('getRecordTypeId Running...');
        Id devRecordTypeId = Schema.SObjectType.Invention__c.getRecordTypeInfosByName().get('Anticipated').getRecordTypeId();
        return devRecordTypeId;
    }
}