WS_INTEGRATION/Sandbox/src/objects/Division__c.object
<CustomObject>
    <description>Flat table that is manually maintained by the admin. This table handles the list of Campus, School, Unit, Department, and Cost Center</description>
    <label>Division</label>
    <nameField>
        <label>Name (Auto-named)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/Sandbox/src/objects/Invention__c.object
<CustomObject>
    <description>Publicly disclosed inventions from KU</description>
    <fields>
        <fullName>Lead_Inventor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lead Inventor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Primary Inventions</relationshipLabel>
        <relationshipName>PrimaryInventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invention</label>
    <nameField>
        <label>Invention Track Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/DX Sandbox/src/objects/Invention__c.object
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Inventions1</relationshipName>
        <type>Lookup</type>
    </fields>

WS_INTEGRATION/DX Sandbox/src/objects/Invention__c.object
    <fields>
        <fullName>Invention_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invention Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions (Invention Contact)</relationshipLabel>
        <relationshipName>Inventions</relationshipName>
        <type>Lookup</type>
    </fields>

SourceOrg/src/objects/Invention__c.object
    <fields>
        <fullName>Invention_Name__c</fullName>
        <description>Name of the Invention</description>
        <inlineHelpText>Name of the Invention</inlineHelpText>
        <label>Invention Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>

WS_INTEGRATION/Sandbox/src/objects/Invention_Contact__c.object
<CustomObject>
    <description>Connects Inventions to Contacts</description>
    <fields>
        <fullName>Contact_Account_Link__c</fullName>
        <description>This returns a relative link to the related Contact Account in Lightning Experience. This is used to create a link to the object in a data table in a Lightning Component.</description>
        <formula>IF(NOT(ISBLANK(Contact_Account__c)),&quot;/lightning/r/Account/&quot;&amp;Contact_Account__r.Id&amp;&quot;/view&quot;,&quot;&quot;)</formula>
        <inlineHelpText>This returns a relative link to the related Contact Account in Lightning Experience.</inlineHelpText>
        <label>Contact Account Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Account_Name__c</fullName>
        <description>Name of the Contact Account on the Invention Contact record. This is used so Lightning Components can access related object data.</description>
        <formula>Contact_Account__r.Name</formula>
        <inlineHelpText>Name of the Contact Account on the Invention Contact record.</inlineHelpText>
        <label>Contact Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Account the Researcher is associated with</inlineHelpText>
        <label>Contact Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventions by Researcher</relationshipLabel>
        <relationshipName>Contact_Inventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_Link__c</fullName>
        <description>This returns a relative link to the related Division in Lightning Experience. This is used to create a link to the object in a data table in a Lightning Component.</description>
        <formula>IF(NOT(ISBLANK(Division__c)),&quot;/lightning/r/Division__c/&quot;&amp;Division__r.Id&amp;&quot;/view&quot;,&quot;&quot;)</formula>
        <inlineHelpText>This returns a relative link to the related Division in Lightning Experience.</inlineHelpText>
        <label>Division Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>Name of the Division on the Invention Contact Record. This is used so Lightning Components can access related object data.</description>
        <formula>Division__r.Name</formula>
        <inlineHelpText>Name of the Division on the Invention Contact Record.</inlineHelpText>
        <label>Division Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Division related to the Researcher. Should be limited to only those associated with the Researcher.
If you do not see the appropriate Division, please check to make sure the Researcher has the Division associated.</inlineHelpText>
        <label>Division</label>
        <referenceTo>Division__c</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Inventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invention_Link__c</fullName>
        <description>This returns a relative link to the related Invention in Lightning Experience. This is used to create a link to the object in a data table in a Lightning Component.</description>
        <formula>IF(NOT(ISBLANK(Invention__c)),&quot;/lightning/r/Invention__c/&quot;&amp;Invention__r.Id&amp;&quot;/view&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This returns a relative link to the related Invention in Lightning Experience.</inlineHelpText>
        <label>Invention Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invention_Name__c</fullName>
        <description>Name of the Division on the Invention Contact Record. This is used so Lightning Components can access related object data.</description>
        <formula>Invention__r.Name</formula>
        <inlineHelpText>Name of the Division on the Invention Contact Record.</inlineHelpText>
        <label>Invention Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invention__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Invention</label>
        <referenceTo>Invention__c</referenceTo>
        <relationshipLabel>Researchers</relationshipLabel>
        <relationshipName>Invention_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Inventor_Text__c</fullName>
        <formula>IF( Lead_Inventor__c, &quot;Yes&quot;,&quot;No&quot;)</formula>
        <label>Lead Inventor Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Inventor__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only one person may have this flag. If you chose this Contact as lead, all others will be marked as not the lead.</inlineHelpText>
        <label>Lead Inventor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Researcher_Link__c</fullName>
        <description>This returns a relative link to the related Researcher (Contact) in Lightning Experience. This is used to create a link to the object in a data table in a Lightning Component.</description>
        <formula>IF(NOT(ISBLANK(Researcher__c)),&quot;/lightning/r/Contact/&quot;&amp;Researcher__r.Id&amp;&quot;/view&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This returns a relative link to the related Researcher in Lightning Experience.</inlineHelpText>
        <label>Researcher Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Researcher_Name__c</fullName>
        <description>Name of the Researcher on the Invention Contact Record. This is used so Lightning Components can access related object data.</description>
        <formula>IF( 
ISBLANK(Researcher__r.Title) , 
&quot;&quot;, 
Researcher__r.Title &amp; &quot; &quot; 
) 
&amp; 
IF( 
ISBLANK(Researcher__r.FirstName) , 
&quot;&quot;, 
Researcher__r.FirstName &amp; &quot; &quot; 
) 
&amp; 
Researcher__r.LastName</formula>
        <inlineHelpText>Name of the Researcher on the Invention Contact Record.</inlineHelpText>
        <label>Researcher Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Researcher__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Researcher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Invention_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Invention Contact</label>
    <nameField>
        <label>Invention Researcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/Sandbox/src/classes/InventionResearcherController.cls
/*
 * Controller for Invention Researcher Lightning Component
 * Test Class: InventionResearcherController_Test
 */
public class InventionResearcherController {

    //Returns list of Invention contacts related to an Invention
    @AuraEnabled
    public static List<Invention_Contact__c> getInventionContacts(Id invId) {
        return [
            SELECT Id, Name, Lead_Inventor__c, Lead_Inventor_Text__c,
            Researcher__c, Researcher_Name__c, Researcher_Link__c,
            Contact_Account__c, Contact_Account_Name__c, Contact_Account_Link__c, 
            Division__c, Division_Name__c, Division_Link__c,
            Invention__c, Invention_Name__c, Invention_Link__c
            FROM Invention_Contact__c
            WHERE Invention__c = :invId
            ORDER BY Lead_Inventor__c DESC];
    }
    
    //Deletes a single Invention contact
    @AuraEnabled
    public static Invention_Contact__c deleteInventionContact(Invention_Contact__c i2c) {
        delete i2c;
        return i2c;
    }
}