WS_INTEGRATION/Sandbox/src/objects/Invention__c.object
<CustomObject>
    <description>Publicly disclosed inventions from KU</description>
    <fields>
        <fullName>Location__c</fullName>
        <description>Campus origin of the invention</description>
        <inlineHelpText>Select the Campus this invention originated from</inlineHelpText>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Lawrence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Center</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invention</label>
    <nameField>
        <label>Invention Track Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/DX Sandbox/src/objects/Invention__c.object
    <fields>
        <fullName>Invention_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invention Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions (Invention Contact)</relationshipLabel>
        <relationshipName>Inventions</relationshipName>
        <type>Lookup</type>
    </fields>

WS_INTEGRATION/Sandbox/src/objects/Invention_Contact__c.object
<CustomObject>
    <description>Connects Inventions to Contacts</description>
    <fields>
        <fullName>Contact_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Account the Researcher is associated with</inlineHelpText>
        <label>Contact Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventions by Researcher</relationshipLabel>
        <relationshipName>Contact_Inventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invention__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Invention</label>
        <referenceTo>Invention__c</referenceTo>
        <relationshipLabel>Researchers</relationshipLabel>
        <relationshipName>Invention_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Researcher__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Researcher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventions</relationshipLabel>
        <relationshipName>Invention_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Invention Contact</label>
    <nameField>
        <label>Invention Researcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invention Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/Sandbox/src/classes/Lookup_Test.cls
/**
* Tests Lookup
**/
@isTest
private class Lookup_Test{
    
    // Create common test data
    @testSetup static void setup() {
        Account a = new Account(Name='Account');
        insert a;
        Contact c = new Contact(FirstName='First',LastName='Last',AccountId=a.Id);
        insert c;
        Invention__c i = new Invention__c(Name='Invention',Location__c='Lawrence');
        insert i;
        Invention_Contact__c ic = new Invention_Contact__c(Name='InventionContact',Researcher__c=c.Id,Contact_Account__c=a.Id,Invention__c=i.Id);
        insert ic;        
    }
    
    //test get InventionResearcherController.getInventionContacts
    @isTest static void testSearchDB()
    {
        Lookup.searchDB('Account', 'Name', 'Id', 5, 'Name', 'Account');
    }
    
    //test InventionResearcherController.deleteInventionContact
    @isTest static void testSearchDB_Id()
    {
        List<Contact> cs = [SELECT Id FROM Contact LIMIT 1];
        Lookup.searchDB_Id('Invention__c', 'Name', 'Id', 5, 'Id', cs[0].Id, 'Invention__c', 'Invention_Contact__c', 'Researcher__c');
    }
}