WS_INTEGRATION/DX Sandbox/src/objects/Invention__c.object
<CustomObject>
    <description>Publicly disclosed inventions from KU</description>
    <fields>
        <fullName>Location__c</fullName>
        <description>Campus responsibility of the invention</description>
        <inlineHelpText>Select the Campus with primary responsibility for this invention.</inlineHelpText>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Lawrence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Center</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invention</label>
    <nameField>
        <label>Invention Track Code (Autonamed)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WS_INTEGRATION/mdapi_output_dir/objects/Invention__c.object
    <recordTypes>
        <fullName>Anticipated</fullName>
        <active>true</active>
        <description>This invention has not been disclosed formally to KU.</description>
        <label>Anticipated</label>
    </recordTypes>

WS_INTEGRATION/DX Sandbox/src/classes/inventionAura.cls
public class inventionAura {
//Pull the record type picklist values-----------------------------------------------------------------------------------------------
    @AuraEnabled    
    public static List<String> getLocationValues(){
        System.debug('getLocationValues() Running...');
        List<String> campusValue = new List<String>();
        
        Schema.DescribeFieldResult fieldResult = Invention__c.Location__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for(Schema.PicklistEntry f: ple){
            campusValue.add(f.getLabel());
        }
        
        return campusValue;
    }
    
    //Get Record Type ID ------------------------------------------
    @AuraEnabled
    public static String getRecordTypeId() {
        System.debug('getRecordTypeId Running...');
        Id devRecordTypeId = Schema.SObjectType.Invention__c.getRecordTypeInfosByName().get('Anticipated').getRecordTypeId();
        return devRecordTypeId;
    }
}