SourceOrg/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source_Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related Source Organization</description>
        <inlineHelpText>Related Source Organization</inlineHelpText>
        <label>Contact Source Organization</label>
        <referenceTo>Source_Organization__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SourceOrg/src/objects/Interaction__c.object
<CustomObject>
    <description>Object to capture Interactions from the source systems including, interactive events(sessions/seminars/classes) and one-way communication (job posting, contact report) etc.</description>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <description>Agreement Type For KUCTC Agreement Data From Sophia</description>
        <inlineHelpText>Agreement Type For KUCTC Agreement Data From Sophia</inlineHelpText>
        <label>Agreement Type</label>
        <picklist>
            <controllingField>Interaction_Type__c</controllingField>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential Disclosure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential Disclosure - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Sponsored Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Sponsored Research - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Institutional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License - Exclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License - Exclusive - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License - Mixed Exclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License - Mixed Exclusive - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License - Non-Exclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License - Non-Exclusive - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Service - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Transfer - Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Transfer - Inbound - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Transfer - Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Transfer - Outbound - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memorandum of Understanding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Memorandum of Understanding - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other - Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_KU_Division__c</fullName>
        <description>KU Division that provided the data.</description>
        <inlineHelpText>KU Division that provided the data.</inlineHelpText>
        <label>Engagement Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Center For Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_System_ID__c</fullName>
        <description>Unique identifier from KU Division datasource for this engagement transaction (where available).</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from KU Division datasource for this engagement transaction (where available).</inlineHelpText>
        <label>Engagement Source System ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_System__c</fullName>
        <description>Source System From Where The Interaction Was Imported</description>
        <inlineHelpText>Source System From Where The Interaction Was Imported</inlineHelpText>
        <label>Engagement Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reggie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sophia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Symplicity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Entry</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <description>Type of Engagement.</description>
        <inlineHelpText>Type of Engagement.</inlineHelpText>
        <label>Engagement Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Company Onsite Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Executive Briefing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Key Executive Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - KU Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Seminar By Firm At KU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event - Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event - Continuing Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job/Placement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job/Placement Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Posting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Invention Disclosure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Patent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Committee Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Campus Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Grant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_Organization__c</fullName>
        <label>Source Organization</label>
        <referenceTo>Source_Organization__c</referenceTo>
        <relationshipLabel>Engagements</relationshipLabel>
        <relationshipName>Related_Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Event Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Interaction_Type__c</controllingField>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anticipated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ask Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned To 3rd Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulkdelete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate (Entity Deceased)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraudulent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long-term Cultiv/Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nationalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Engagement</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Engagement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/objects/Source_Organization__c.object
<CustomObject>
    <description>Organization data flowing into Salesforce or imported  from one of the multiple Source Systems (Including but not limited to PS Financials, Advance, Reggie, Sofia)</description>
    <fields>
        <fullName>Master_Organization__c</fullName>
        <description>This is the Master Organization that the Source Organization is an entity/part of</description>
        <label>Master Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Source Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Source Organization</label>
    <nameField>
        <label>Source Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/classes/ContactUpdateOnSrcOrgUpdateTest.cls
@isTest
private class ContactUpdateOnSrcOrgUpdateTest {

   private static testMethod void ContactUpdateOnSrcOrgUpdateTriggerTest(){
     
     Account a = new Account (Name='TestAccount789');
     insert a;
     
     Account aa = new Account (Name='TestAccount147');
     insert aa;
     
     Source_Organization__c so = new Source_Organization__c (Name ='TestSourceAccount789', Master_Organization__c = aa.Id);
     insert so;
     
     so = [Select Id, Master_Organization__c From Source_Organization__c WHERE Id = :so.Id];
     
     Contact co = new Contact (RecordTypeId='012i00000015Qwj',
     Contact_Source_Organization__c = so.Id,
     LastName = 'TestContact789',
     FirstName = 'Tester'
     );
     
     insert co;
     
     Interaction__c i = new Interaction__c (RecordTypeId='012i00000015Qwl',
     Source_Organization__c = so.Id,
     Interaction_Type__c = 'Agreement',
     Interaction_Source_System_ID__c = 'ApexIt2013456',
     Agreement_Type__c = 'Other',
     Status__c = 'Expired',
     Interaction_Source_System__c = 'Other',
     Interaction_Source_KU_Division__c = 'Technology Transfer'
     );
     
     insert i;
     
     
  
     Test.startTest();
    
    so.Master_Organization__c = a.Id;
    
    update so;
    
    so = [Select Id, Master_Organization__c From Source_Organization__c WHERE Id = :so.Id];
    
    update co;
    
    co = [Select Id, Contact_Source_Organization__c, AccountId From Contact Where Id=: co.Id];
    
    update i;
    
    i = [Select Id, Source_Organization__c, Related_Master_Organization__c From Interaction__c Where Id=: i.Id];
    
    System.assertEquals(co.AccountId, so.Master_Organization__c);
    System.assertEquals(i.Related_Master_Organization__c, so.Master_Organization__c);
     
     Test.stopTest();

}
}