SourceOrg/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source_Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related Source Organization</description>
        <inlineHelpText>Related Source Organization</inlineHelpText>
        <label>Contact Source Organization</label>
        <referenceTo>Source_Organization__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SourceOrg/src/objects/Source_Organization__c.object
<CustomObject>
    <description>Organization data flowing into Salesforce or imported  from one of the multiple Source Systems (Including but not limited to PS Financials, Advance, Reggie, Sofia)</description>
    <fields>
        <fullName>Master_Organization__c</fullName>
        <description>This is the Master Organization that the Source Organization is an entity/part of</description>
        <label>Master Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Source Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Source Organization</label>
    <nameField>
        <label>Source Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/classes/ContactMasterAccountUpdateTest.cls
@isTest
private class ContactMasterAccountUpdateTest {

   private static testMethod void ContactMasterAccountUpdateTriggerTest(){
     
     Account a = new Account (Name='TestAccount456');
     insert a;
     
     Source_Organization__c so = new Source_Organization__c (Name ='TestSourceAccount456', Master_Organization__c = a.Id);
     insert so;
     
     so = [Select Id, Master_Organization__c From Source_Organization__c WHERE Id = :so.Id];
     
     Contact co = new Contact (RecordTypeId='012i00000015Qwj',
     Contact_Source_Organization__c = so.Id,
     LastName = 'TestContact456',
     FirstName = 'Tester'
     );
     
     insert co;
     
     co = [Select Id, Contact_Source_Organization__c, AccountId From Contact Where Id=: co.Id];
     
     
     
     
     Test.startTest();
    
    System.assertEquals(co.AccountId, so.Master_Organization__c);
     
     Test.stopTest();

}
}