SourceOrg/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Source_System_Last_Modified_Date__c</fullName>
        <description>Date when the source system record was last modified in the source system</description>
        <inlineHelpText>Date when the source system record was last modified in the source system</inlineHelpText>
        <label>Source System Last Modified Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SourceOrg/src/objects/Interaction__c.object
<CustomObject>
    <description>Object to capture Interactions from the source systems including, interactive events(sessions/seminars/classes) and one-way communication (job posting, contact report) etc.</description>
    <fields>
        <fullName>Activity_Due_Date__c</fullName>
        <description>Due Date of an Activity</description>
        <inlineHelpText>Due Date of an Activity</inlineHelpText>
        <label>Activity Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User the Task or Event is assigned to</description>
        <inlineHelpText>User the Task or Event is assigned to</inlineHelpText>
        <label>Assigned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Engagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <description>Date Of Creation In Source System</description>
        <inlineHelpText>Date Of Creation In Source System</inlineHelpText>
        <label>Source System Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description of the event</description>
        <inlineHelpText>Provide a description of the event</inlineHelpText>
        <label>Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date/Time</description>
        <inlineHelpText>Enter End Date/Time</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_KU_Division__c</fullName>
        <description>KU Division that provided the data.</description>
        <inlineHelpText>KU Division that provided the data.</inlineHelpText>
        <label>Engagement Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Center For Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_System_ID__c</fullName>
        <description>Unique identifier from KU Division datasource for this engagement transaction (where available).</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from KU Division datasource for this engagement transaction (where available).</inlineHelpText>
        <label>Engagement Source System ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_System__c</fullName>
        <description>Source System From Where The Interaction Was Imported</description>
        <inlineHelpText>Source System From Where The Interaction Was Imported</inlineHelpText>
        <label>Engagement Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reggie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sophia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Symplicity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Entry</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <description>Type of Engagement.</description>
        <inlineHelpText>Type of Engagement.</inlineHelpText>
        <label>Engagement Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Company Onsite Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Executive Briefing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Key Executive Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - KU Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Seminar By Firm At KU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event - Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event - Continuing Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job/Placement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job/Placement Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Posting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Invention Disclosure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Patent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Committee Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Campus Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Grant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location of Interaction</description>
        <inlineHelpText>Location of Interaction</inlineHelpText>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Related_Master_Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Master Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagements</relationshipLabel>
        <relationshipName>Interactions_Of_MasterOrg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Organization__c</fullName>
        <label>Source Organization</label>
        <referenceTo>Source_Organization__c</referenceTo>
        <relationshipLabel>Engagements</relationshipLabel>
        <relationshipName>Related_Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_System_Last_Modified_Date__c</fullName>
        <description>Last Modified Date In The Source System</description>
        <inlineHelpText>Last Modified Date In The Source System</inlineHelpText>
        <label>Source System Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date/Time</description>
        <inlineHelpText>Enter Start Date/Time</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Task Subject</description>
        <inlineHelpText>Task Subject</inlineHelpText>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Engagement</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Engagement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/objects/Source_Organization__c.object
<CustomObject>
    <description>Organization data flowing into Salesforce or imported  from one of the multiple Source Systems (Including but not limited to PS Financials, Advance, Reggie, Sofia)</description>
    <fields>
        <fullName>Source_System_Last_Modified_Date__c</fullName>
        <description>Last modified date in the source system.</description>
        <inlineHelpText>Last modified date in the source system.</inlineHelpText>
        <label>Source System Last Modified Date</label>
        <type>Date</type>
    </fields>
    <label>Source Organization</label>
    <nameField>
        <label>Source Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/classes/createEventEngagements.cls
Global class createEventEngagements implements Database.Batchable <sObject>
{

 Global static id batchManualKickOff()
    {
        Id batchInstanceId = Database.executeBatch(new createEventEngagements()); 
        return batchInstanceId;
    }

 Global Database.querylocator start (Database.BatchableContext BC)
 {
 String query = 'Select Id, WhatId, Master_Org_s_Primary_Source_Org_Id__c,User_Profile_Id__c, Type, CreatedDate, Description, OwnerId, EndDateTime, Subject, Location, StartDateTime, LastModifiedDate, Activity_Converted_to_Engagement__c From Event';
 return Database.getQueryLocator(query);
 }

 Global void execute (Database.BatchableContext BC, List<sObject> scope)
 {
 List <sObject> evList = new List <sObject>();
 List < Interaction__c> engList = new List < Interaction__c>();
 List<Interaction__c> engToUpdate = new List<Interaction__c>();
 
  for (sObject s: scope)
 {
   if (string.valueOf(s.get('WhatId'))!=null && string.valueOf(s.get('Master_Org_s_Primary_Source_Org_Id__c'))!=null && string.valueOf(s.get('Type'))!=null)
  {
  system.debug(' /before the first if 1 ' + string.valueOf(s.get('WhatId')).substring(0, 3));
  string myDateT = string.valueOf(date.today());
  string myDateY = string.valueOf(date.today()-1);
  string myDateTo = string.valueOf(date.today()+1);
  string createdDate = string.valueOf( s.get('CreatedDate') ).substring(0, 10);
  string LastModifiedDate = string.valueOf( s.get('LastModifiedDate') ).substring(0, 10);
  string whatIdKey = '001';
  string createdByProfileId = '00ei0000000GtR2';
  string strWhatId = string.valueOf(s.get('WhatId')).substring(0, 3);
  string strCreatedByProfileId = String.valueOf(s.get('User_Profile_Id__c'));
  string eventType = string.valueOf(s.get('Type'));
  string call = 'Engagement - Call';
  string email = 'Engagement - Email';
  string eb = 'Engagement - Executive Briefing';
  string cov = 'Engagement - Company Onsite Visit';
  string kev = 'Engagement - Key Executive Visit';
  string kv = 'Engagement - KU Visit';
  string se = 'Engagement - Seminar By Firm At KU';
  string wo = 'Engagement - Seminar By Firm At KU';
  
  if (String.valueOf(s.get('Activity_Converted_to_Engagement__c')) == 'false')
  {
  if (createdDate <= myDateT)
  //if (LastModifiedDate == myDateT || LastModifiedDate == myDateY || LastModifiedDate == myDateTo)
  {
  if (strWhatId == whatIdKey)
  {
  if (strCreatedByProfileId == createdByProfileId )
  {
  s.put('Activity_Converted_to_Engagement__c', true);
  
  Interaction__c eng = new Interaction__c();
  eng.Description__c = String.valueOf( s.get('Description') );
  eng.Assigned_To__c = String.valueOf( s.get('OwnerId') );
  eng.Location__c = string.valueOf( s.get('Location'));
  eng.Start_Date__c = date.valueOf( s.get('StartDateTime'));
  eng.End_Date__c = date.valueOf( s.get('EndDateTime') );
  eng.Subject__c = String.valueOf( s.get('Subject') );
  eng.Source_Organization__c =String.valueOf( s.get('Master_Org_s_Primary_Source_Org_Id__c') );
  eng.Related_Master_Organization__c = String.valueOf( s.get('whatid') );
  eng.Interaction_Type__c = String.valueOf( s.get('Type') );
  eng.Interaction_Source_KU_Division__c = 'Corporate Partnerships';
  //eng.CreatedBy.Id = String.valueOf( s.get('Createdby.Id') );
  eng.Created_Date__c = date.valueOf( s.get('CreatedDate') );
  eng.Source_System_Last_Modified_Date__c = date.valueOf( s.get('LastModifiedDate') );
  eng.Interaction_Source_System__c = 'SFDC';
  eng.Interaction_Source_System_ID__c = String.valueOf( s.get('Id') );
  
  if (String.valueOf( s.get('Type') )== call ||  String.valueOf( s.get('Type')) == email)
  {
  eng.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Calls & Emails').getRecordTypeId();
  }
  else if (String.valueOf( s.get('Type') )== eb)
  {
  eng.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Executive Briefings').getRecordTypeId();
  }
  else if (string.valueOf(s.get('Activity_Converted_to_Engagement__c')) == 'true')
  {
  eng.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Company Visits & Contact Activities').getRecordTypeId();
  }
  
  
  engList.add (eng);
  
  evList.add(s);
  }
  }
  }
  }
  else
  {
  if (LastModifiedDate == myDateT || LastModifiedDate == myDateY || LastModifiedDate == myDateTo)
  {
  if (strWhatId == whatIdKey)
  {
  if (strCreatedByProfileId == createdByProfileId )
  {
  Map <string, sObject> evMap = new Map <string, sObject>();
  evMap.put(String.valueOf( s.get('Id') ), s);
  
  List < Interaction__c> intList = [select Id,RecordTypeId, Location__c, Start_Date__c, End_Date__c, Description__c, Assigned_To__c, Activity_Due_Date__c, Subject__c, Source_Organization__c, Related_Master_Organization__c, Interaction_Type__c, Interaction_Source_KU_Division__c, Created_Date__c, Source_System_Last_Modified_Date__c, Interaction_Source_System__c, Interaction_Source_System_ID__c From Interaction__c Where Interaction_Source_System_ID__c in :evMap.keyset() ];
  for (Interaction__c inte: intList){
  if (null!=inte.Interaction_Source_System_ID__c)
    {
    sObject ss = evMap.get(inte.Interaction_Source_System_ID__c);
    inte.Description__c =string.valueof(ss.get('Description'));
    inte.Assigned_To__c = String.valueOf( ss.get('OwnerId') );
    inte.Location__c = string.valueOf( s.get('Location'));
    inte.Start_Date__c = date.valueOf( s.get('StartDateTime'));
    inte.End_Date__c = date.valueOf( s.get('EndDateTime') );
    inte.Subject__c = String.valueOf( ss.get('Subject') );
    //inte.Source_Organization__c =String.valueOf( ss.get('Master_Org_s_Primary_Source_Org_Id__c') );
    inte.Related_Master_Organization__c = String.valueOf( ss.get('whatid') );
    inte.Interaction_Type__c = String.valueOf( ss.get('Type') );
    inte.Interaction_Source_KU_Division__c = 'Corporate Partnerships';
    //inte.CreatedBy.Id = String.valueOf( ss.get('Createdby.Id') );
    inte.Created_Date__c = date.valueOf( ss.get('CreatedDate') );
    inte.Source_System_Last_Modified_Date__c = date.valueOf( ss.get('LastModifiedDate') );
    inte.Interaction_Source_System__c = 'SFDC';
    
    if (String.valueOf( s.get('Type') )== call ||  String.valueOf( s.get('Type')) == email)
    {
    inte.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Calls & Emails').getRecordTypeId();
    }
    else if (String.valueOf( s.get('Type') )== eb)
    {
    inte.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Executive Briefings').getRecordTypeId();
    }
    else
    {
    inte.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Company Visits & Contact Activities').getRecordTypeId();
    }
  
    engToUpdate.add(inte);
    }
  }
  }
  }
  }
  }
  }
  }
  insert engList;
  
  update evList;
  
  update engToUpdate;
 }
 
 global void finish (Database.BatchableContext BC)
 {
 }
}