SourceOrg/src/objects/Interaction__c.object
<CustomObject>
    <description>Object to capture Interactions from the source systems including, interactive events(sessions/seminars/classes) and one-way communication (job posting, contact report) etc.</description>
    <fields>
        <fullName>Activity_Due_Date__c</fullName>
        <description>Due Date of an Activity</description>
        <inlineHelpText>Due Date of an Activity</inlineHelpText>
        <label>Activity Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User the Task or Event is assigned to</description>
        <inlineHelpText>User the Task or Event is assigned to</inlineHelpText>
        <label>Assigned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Engagements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <description>Date Of Creation In Source System</description>
        <inlineHelpText>Date Of Creation In Source System</inlineHelpText>
        <label>Source System Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description of the event</description>
        <inlineHelpText>Provide a description of the event</inlineHelpText>
        <label>Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_KU_Division__c</fullName>
        <description>KU Division that provided the data.</description>
        <inlineHelpText>KU Division that provided the data.</inlineHelpText>
        <label>Engagement Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Center For Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_System_ID__c</fullName>
        <description>Unique identifier from KU Division datasource for this engagement transaction (where available).</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from KU Division datasource for this engagement transaction (where available).</inlineHelpText>
        <label>Engagement Source System ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Source_System__c</fullName>
        <description>Source System From Where The Interaction Was Imported</description>
        <inlineHelpText>Source System From Where The Interaction Was Imported</inlineHelpText>
        <label>Engagement Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PeopleSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reggie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sophia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Symplicity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Entry</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <description>Type of Engagement.</description>
        <inlineHelpText>Type of Engagement.</inlineHelpText>
        <label>Engagement Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Company Onsite Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Executive Briefing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Key Executive Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - KU Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Seminar By Firm At KU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement - Workshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event - Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event - Continuing Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job/Placement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job/Placement Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Posting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Invention Disclosure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Patent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Committee Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Campus Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Grant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority For Tasks imported as Engagements</description>
        <inlineHelpText>Priority For Tasks imported as Engagements</inlineHelpText>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Master_Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Master Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Engagements</relationshipLabel>
        <relationshipName>Interactions_Of_MasterOrg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Organization__c</fullName>
        <label>Source Organization</label>
        <referenceTo>Source_Organization__c</referenceTo>
        <relationshipLabel>Engagements</relationshipLabel>
        <relationshipName>Related_Interactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_System_Last_Modified_Date__c</fullName>
        <description>Last Modified Date In The Source System</description>
        <inlineHelpText>Last Modified Date In The Source System</inlineHelpText>
        <label>Source System Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Event Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>Interaction_Type__c</controllingField>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anticipated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ask Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned To 3rd Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulkdelete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate (Entity Deceased)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraudulent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long-term Cultiv/Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nationalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Task Subject</description>
        <inlineHelpText>Task Subject</inlineHelpText>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Engagement</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Engagement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/objects/Source_Organization__c.object
<CustomObject>
    <description>Organization data flowing into Salesforce or imported  from one of the multiple Source Systems (Including but not limited to PS Financials, Advance, Reggie, Sofia)</description>
    <fields>
        <fullName>Source_System_Last_Modified_Date__c</fullName>
        <description>Last modified date in the source system.</description>
        <inlineHelpText>Last modified date in the source system.</inlineHelpText>
        <label>Source System Last Modified Date</label>
        <type>Date</type>
    </fields>
    <label>Source Organization</label>
    <nameField>
        <label>Source Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/classes/createTaskEngagements.cls
Global class createTaskEngagements implements Database.Batchable <sObject>
{

 Global static id batchManualKickOff()
    {
        Id batchInstanceId = Database.executeBatch(new createTaskEngagements()); 
        return batchInstanceId;
    }

 Global Database.querylocator start (Database.BatchableContext BC)
 {
 String query = 'Select Id, WhatId, Master_Org_s_Primary_Source_Org_Id__c,User_Profile_Id__c, Type, CreatedDate, Description, OwnerId, ActivityDate, Subject, Priority, Status, LastModifiedDate, CreatedById, Activity_Converted_to_Engagement__c From Task';
 return Database.getQueryLocator(query);
 }

 Global void execute (Database.BatchableContext BC, List<sObject> scope)
 {
 List <sObject> tList = new List <sObject>();
 List < Interaction__c> engList = new List < Interaction__c>();
 List<Interaction__c> engToUpdate = new List<Interaction__c>();
 
  for (sObject s: scope)
  {
  if (string.valueOf(s.get('WhatId'))!=null && string.valueOf(s.get('Master_Org_s_Primary_Source_Org_Id__c'))!=null && (string.valueOf(s.get('Type'))!=null && string.valueOf(s.get('Type'))!='Other Task'))
  {
  system.debug(' /forsObjectScope ');
  string myDateT = string.valueOf(date.today());
  string myDateY = string.valueOf(date.today()-1);
  string myDateTo = string.valueOf(date.today()+1);
  string createdDate = string.valueOf( s.get('CreatedDate') ).substring(0, 10);
  string LastModifiedDate = string.valueOf( s.get('LastModifiedDate') ).substring(0, 10);
  string whatIdKey = '001';
  string createdByProfileId = '00ei0000000GtR2';
  string strWhatId = String.valueOf(s.get('WhatId')).substring(0 , 3);
  string strCreatedByProfileId = String.valueOf(s.get('User_Profile_Id__c'));
  
  system.debug(' /before the first if 1 ' + string.valueOf(date.today()));
  system.debug(' /before the first if 2 ' + string.valueOf( s.get('CreatedDate') ).substring(0, 10));
  system.debug(' /before the first if 3 ' + string.valueOf(s.get('Activity_Converted_to_Engagement__c')));
  system.debug(' /before the first if 4 ' + string.valueOf( s.get('LastModifiedDate') ).substring(0, 10));
  
  if (string.valueOf(s.get('Activity_Converted_to_Engagement__c')) == 'false')
  {
   system.debug(' /Activity_Converted_to_Engagement__c ');
  if (createdDate <= myDateT)
  //if (LastModifiedDate == myDateT || LastModifiedDate == myDateY || LastModifiedDate == myDateTo)
  {
  system.debug(' /createdDate ');
  if (strWhatId == whatIdKey)
  {
  system.debug(' /WhatId '+ strWhatId);
  if (strCreatedByProfileId == createdByProfileId )
  {
  system.debug(' /profileId ');
  s.put('Activity_Converted_to_Engagement__c', true);
  system.debug(' /putTrueToCheckBox ');
  
  Interaction__c eng = new Interaction__c();
  eng.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Calls & Emails').getRecordTypeId();
  system.debug(' /newInteraction1 ');
  
  eng.Description__c = String.valueOf( s.get('Description') );
  system.debug(' /newInteraction2 '+ String.valueOf( s.get('Description') ) );
  
  eng.Assigned_To__c = String.valueOf( s.get('OwnerId') );
  system.debug(' /newInteraction3 '+ String.valueOf( s.get('OwnerId') ));
  
  eng.Activity_Due_Date__c = date.valueOf( s.get('ActivityDate') );
  system.debug(' /newInteraction4 '+ date.valueOf( s.get('ActivityDate') ));
  
  eng.Subject__c = String.valueOf( s.get('Subject') );
  system.debug(' /newInteraction5 '+ String.valueOf( s.get('Subject') ));
  
  eng.Source_Organization__c =String.valueOf( s.get('Master_Org_s_Primary_Source_Org_Id__c') );
  eng.Related_Master_Organization__c = String.valueOf( s.get('whatid') );
  eng.Interaction_Type__c = String.valueOf( s.get('Type') );
  eng.Interaction_Source_KU_Division__c = 'Corporate Partnerships';
  //eng.CreatedById = String.valueOf( s.get('CreatedById') );
  system.debug(' /newInteraction6 ');
  
  eng.Priority__c = String.valueOf( s.get('Priority') );
  eng.Status__c = String.valueOf( s.get('Status') );
  eng.Created_Date__c = date.valueOf( s.get('CreatedDate') );
  eng.Source_System_Last_Modified_Date__c = date.valueOf( s.get('LastModifiedDate') );
  eng.Interaction_Source_System__c = 'SFDC';
  eng.Interaction_Source_System_ID__c = String.valueOf( s.get('Id') );
  engList.add (eng);
  
  tList.add(s);
  }
  }
  }
  }
  else if (string.valueOf(s.get('Activity_Converted_to_Engagement__c')) == 'true')
  {
  system.debug(' /Updateelse ');
  
  if (LastModifiedDate == myDateT || LastModifiedDate == myDateY || LastModifiedDate == myDateTo)
  {
  system.debug(' /UpdatemodifyiedDate ');
  
  if (strWhatId == whatIdKey)
  {
  system.debug(' /UpdateWhatId ');
  
  if (strCreatedByProfileId == createdByProfileId )
  {
  system.debug(' /Updateprofile ');
  
  Map <string, sObject> tMap = new Map <string, sObject>();
  tMap.put(String.valueOf( s.get('Id') ), s);
  
  system.debug(' /testMap '+ tMap.size());
  
  List < Interaction__c> intList = [select Id,RecordTypeId, Description__c, Assigned_To__c, Activity_Due_Date__c, Subject__c, Source_Organization__c, Related_Master_Organization__c, Interaction_Type__c, Interaction_Source_KU_Division__c, Priority__c, Status__c, Created_Date__c, Source_System_Last_Modified_Date__c, Interaction_Source_System__c, Interaction_Source_System_ID__c From Interaction__c Where Interaction_Source_System_ID__c in :tMap.keyset() ];
  system.debug(' /test intlist '+ intList.size());
  
  for (Interaction__c inte: intList){
  if (null!=inte.Interaction_Source_System_ID__c)
    {
    system.debug(' /Updateinte ');
    sObject ss = tMap.get(inte.Interaction_Source_System_ID__c);
    inte.RecordTypeId = Schema.SObjectType.Interaction__c.getRecordTypeInfosByName().get('Calls & Emails').getRecordTypeId();
    inte.Description__c =string.valueof(ss.get('Description'));
    inte.Assigned_To__c = String.valueOf( ss.get('OwnerId') );
    inte.Activity_Due_Date__c = date.valueOf( ss.get('ActivityDate') );
    inte.Subject__c = String.valueOf( ss.get('Subject') );
    //inte.Source_Organization__c =String.valueOf( ss.get('Master_Org_s_Primary_Source_Org_Id__c') );
    inte.Related_Master_Organization__c = String.valueOf( ss.get('whatid') );
    inte.Interaction_Type__c = String.valueOf( ss.get('Type') );
    inte.Interaction_Source_KU_Division__c = 'Corporate Partnerships';
    //inte.CreatedBy.Id = String.valueOf( ss.get('CreatedbyId') );
    inte.Priority__c = String.valueOf( ss.get('Priority') );
    inte.Status__c = String.valueOf( ss.get('Status') );
    inte.Created_Date__c = date.valueOf( ss.get('CreatedDate') );
    inte.Source_System_Last_Modified_Date__c = date.valueOf( ss.get('LastModifiedDate') );
    inte.Interaction_Source_System__c = 'SFDC';
    engToUpdate.add(inte);
    }
  }
  }
  }
  }
  }
  }
  system.debug(' /test englist '+ engList.size());
  system.debug(' /test tlist '+ tList.size());
  system.debug(' /test engtoupdatelist '+ engToUpdate.size());
  }
 insert engList;
  
 update tList;
  
 update engToUpdate;
 }
 
 global void finish (Database.BatchableContext BC)
 {
 }
}