SourceOrg/src/objects/Source_Organization__c.object
<CustomObject>
    <description>Organization data flowing into Salesforce or imported  from one of the multiple Source Systems (Including but not limited to PS Financials, Advance, Reggie, Sofia)</description>
    <fields>
        <fullName>Master_Organization__c</fullName>
        <description>This is the Master Organization that the Source Organization is an entity/part of</description>
        <label>Master Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Source Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Source_Org__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to Flag one of the Source Organizations related to a Master Organization as &quot;Primary&quot;.
Checked if this is Primary Source Org for the Master.</description>
        <inlineHelpText>Used to Flag one of the Source Organizations related to a Master Organization as &quot;Primary&quot;. Check this if this is Primary Source Org for the Master</inlineHelpText>
        <label>Primary Source Org?</label>
        <type>Checkbox</type>
    </fields>
    <label>Source Organization</label>
    <nameField>
        <label>Source Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SourceOrg/src/classes/updateActivityPSOTest.cls
@isTest
public class updateActivityPSOTest {
public static testMethod void updateActivityPSOTriggerTest() {

Datetime sdt = Datetime.now();
Datetime edt = Datetime.now() + (0.024305);

Account mo = new Account (Name='Test MO 6/16/2014');
     
insert mo;

Source_Organization__c pso = new Source_Organization__c ( Name='Test PSO 6/16/2014', Master_Organization__c = mo.Id, Primary_Source_Org__c = True );
     
insert pso;

string psoId = pso.Id;

Update mo;

Task t = new Task (WhatId = mo.Id, Subject = 'Call', Status = 'Not Started', Priority = 'High', Type = 'Engagement - Call');

insert t;

Event ev = new Event (WhatId = mo.Id, Subject = 'Meeting', Type = 'Engagement - Key Executive Visit', StartDateTime= sdt, EndDateTime= edt);

insert ev;

Test.StartTest();

update mo;
update t;
update ev;

t = [SELECT Id, Master_Org_s_Primary_Source_Org_Id__c FROM Task WHERE Id = :t.Id];

ev = [SELECT Id, Master_Org_s_Primary_Source_Org_Id__c FROM Event WHERE Id=:ev.Id];

system.AssertEquals(psoId,t.Master_Org_s_Primary_Source_Org_Id__c);

system.AssertEquals(psoId,ev.Master_Org_s_Primary_Source_Org_Id__c);

Test.stopTest();
}
}